### ISSUE TITLE
Feature request (Google/Alexa manager)

### ISSUE THREAD

**Issue by caiosweet** [jumping2000/notifier#18]
# Media player e notifiche audio
- [ ] Escludere servizio Google o Alexa.
- [ ] Includere più media player (list) o tutti.
- [ ] flessibilità opzioni.
- [ ] Invio suoni o file audio (solo a inizio messaggio?).
- [ ] false |  no | 0  (0 per mantenere compatibilità).
- [ ] true | yes | 1  (1 per mantenere compatibilità).
- [ ] Migliorare gestione volumi? (Vedi se player in riproduzione).
- [ ] Async (o evitare che un servizio blocchi il successivo se da errore).

# Esempi
Esempio di funzionalità include ed esclude

```
google: false (esclusione del servizio, pari a switch off)

(riproduzione su questa lista usando entity o friendly_name) 
media_player_alexa: 
	- media_player.xxx
	- media_player.yyy

media_player_alexa: sala,studio 

media_player_alexa:
	- sala
	- studio
```

Flessibilità opzioni (anche per le notifiche testo poi vediamo)

```
alexa: # (tutto ciò inerente alexa)
	volume: 0.5
	voice: giorgio
	player: sala,studio #(o media_player: xx,yy)
	sound: clock #(da vedere se gestire una libreria)
	# oppure 
	# audio: soundbank://soundlibrary/foley/amzn_sfx_clock_ticking_01

```

```
alexa: no
google: # (tutto ciò inerente google)
	volume: 0.3
	media: \local\media\mio.mp3
	player: red,black (o anche all) #(o media_player: xxx)
```

**Comment by jumping2000** [comment]
ok
