### ISSUE TITLE
"bug" in google notifier

### ISSUE THREAD

**Issue by jokerigno** [jumping2000/notifier#34]
Ciao Giampi,

ho notato forse un bug nel notifier quando il messaggio audio è particolarmente lungo. In pratica succede che il volume viene reimpostato al livello base del periodo della giornata (mattina-pomeriggio-sera-ecc) mentre il media_player sta ancora parlando. 

Pensi sia possibile creare un wait che aspetta che il media_player usato sia in idle prima di cambiare di nuovo il volume al livello precedente?

Fammi sapere se posso aiutarti in qualsiasi modo

Ciao

**Comment by jumping2000** [comment]
Come detto è già così. l'unica cosa che si può cambiare è l'algoritmo che calcola il tempo di attesa in base al messaggio da inviare.
