### ISSUE TITLE
punti aperti

### ISSUE THREAD

**Issue by jumping2000** [jumping2000/notifier#4]
**Is your feature request related to a problem? Please describe.**

1. Last message 245 se metti il timestamp altrimenti il max 255
 1.1 il restore è valido per google e Alexa, lo lasciamo così o lo rimetti nel file generale?
2. noi usiamo markdown per telegram, meglio prevenire errori vedi .replace("","-") oppure, ma ho riscontrato problemi, forse per via di troppi test, .replace(""," ")
Oppure sosstituire tutti i markdown (*,_,`,etcetc) con '' (dando possibilità con uno switch?)
3. vedi title = [{} - {}] {} ho tolto * centrali
4. come facciamo con il secret.py e secret.yaml? (volendo si può importare il secret.yaml come app.yaml ;)
5. dividiamo le impostazioni delle entity nei file yaml? (google,alexa,ariela)
6. aggiungi push alexa
7. per il tts ariela non c'è la coda... ma per adesso ok!!
8. per i replace dei tts forse tenterò di usare re.sub che ne pensi? (tipo sostituire virgole con punti, esclamazioni con punto etcetc)
9. Al momento nel package restano come automazioni:
id: notification_repeat_last_message_hub
id: send_intercom_message_hub
id: guest_mode_hub
id: create_notification_automation_group_hub
Che intenzioni hai?

per adesso è tutto, questo messaggio si distruggerà dopo la tua lettura :0)

**Comment by caiosweet** [comment]
Per il punto 2, direi che il problema principale possono essere i link.
Ho trovato [questo helper con una def escape_markdown](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/telegram/utils/helpers.py) :0)

**Comment by jumping2000** [comment]
AL momento rimangono da risolvere i punti:
1-6-7-8,  a parte il 6 gli altri non precludono il passaggio in produzione

**Comment by caiosweet** [comment]
Il punto 6(push Alexa) per ora l'ho inserito in worker. Non mi piace, ma funziona.
Sostanzialmente per avere solo i push senza audio basta selezionare push nel selecet di default type/method.
In questo modo lo switch Alexa diventerebbe l'interruttore generale di ciò che riguarda Alexa.
Forse i push alexa/Ariela andrebbero in notifier.?

Ieri guardavo anche un po' async 😅https://community.home-assistant.io/t/announcement-appdaemon-4-0-0-beta-2/143304?u=caiosweet

**Comment by caiosweet** [comment]
Direi che il punto 6 è chiuso.

**Comment by jumping2000** [comment]
Chiudiamo tutto
