### ISSUE TITLE
Bug - with recent update

### ISSUE THREAD

**Issue by Bobsilvio** [jumping2000/notifier#65]
### Home Assistant Core Version

2023.10.5

### Home Assistant Installation Type

Home Assistant Operating System

### Description

<Plugin jumping2000/notifier> Repository structure for 2023.7.0 is not compliant

### Automation YAML config

```yaml
fix
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

fix

### Actual Behaviour

fix

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by jumping2000** [comment]
Non ho capito quale è il bug
