### ISSUE TITLE
Errore centro notifiche

### ISSUE THREAD

**Issue by Bobsilvio** [jumping2000/notifier#66]
### Home Assistant Core Version

2023.10.5

### Home Assistant Installation Type

Home Assistant Supervised

### Description

Errore sicuramente banale della mia configurazione che non riesco a risolvere.

L'automazione "CN FSM Elettrodomestici 2023.10.0 - Asciugatrice" (automation.cn_fsm_elettrodomestici_2023_10_0_asciugatrice) ha un'azione che chiama un servizio sconosciuto: script.my_notify. 

<img width="582" alt="Screenshot 2023-10-29 alle 10 28 18" src="https://github.com/jumping2000/notifier/assets/814211/b84ff890-1a5a-4265-ba58-48f46919df1e">

### Automation YAML config

```yaml
errore
```

### To Reproduce

3. Trigger the automation '....'

### Expected behavior

errore

### Actual Behaviour

errore

### Additional Details

- [ ] I'd like to help developing a fix for this issue.

**Comment by jumping2000** [comment]
Ma scusa perché hai aperto l'issue qui e non su "HA-Template" dove è disponibile il blueprint oppure su "ha-packages"?
cmq allega la schermate del blueprint con i dati che hai inserito. ciao

**Comment by Bobsilvio** [comment]
<img width="1035" alt="Screenshot 2023-10-30 alle 21 28 15" src="https://github.com/jumping2000/notifier/assets/814211/fc8904c6-0089-499a-90e3-5fc586bdffad">
<img width="1035" alt="Screenshot 2023-10-30 alle 21 28 08" src="https://github.com/jumping2000/notifier/assets/814211/fc2e6132-8279-4269-86d7-49356caa2ec1">
<img width="1036" alt="Screenshot 2023-10-30 alle 21 27 57" src="https://github.com/jumping2000/notifier/assets/814211/d74ccacb-d7a6-468b-a702-87d0a3b8b485">
<img width="1035" alt="Screenshot 2023-10-30 alle 21 27 46" src="https://github.com/jumping2000/notifier/assets/814211/a626c6e0-1ee0-44c2-b148-8c1931817919">

**Comment by jumping2000** [comment]
> <img alt="Screenshot 2023-10-30 alle 21 28 15" width="1035" src="https://user-images.githubusercontent.com/814211/279186783-fc8904c6-0089-499a-90e3-5fc586bdffad.png"> <img alt="Screenshot 2023-10-30 alle 21 28 08" width="1035" src="https://user-images.githubusercontent.com/814211/279186788-fc2e6132-8279-4269-86d7-49356caa2ec1.png"> <img alt="Screenshot 2023-10-30 alle 21 27 57" width="1036" src="https://user-images.githubusercontent.com/814211/279186790-d74ccacb-d7a6-468b-a702-87d0a3b8b485.png"> <img alt="Screenshot 2023-10-30 alle 21 27 46" width="1035" src="https://user-images.githubusercontent.com/814211/279186793-a626c6e0-1ee0-44c2-b148-8c1931817919.png">

hai messo "use centro notifiche" quando non hai installato il centro notifiche

**Comment by Bobsilvio** [comment]
se parli di questo: https://github.com/caiosweet/Package-Notification-HUB-AppDaemon
l'ho installato..
<img width="2089" alt="Screenshot 2023-10-31 alle 09 43 55" src="https://github.com/jumping2000/notifier/assets/814211/c16fb6d1-7188-4994-9c2d-91fd93024b13">
<img width="1772" alt="Screenshot 2023-10-31 alle 09 44 36" src="https://github.com/jumping2000/notifier/assets/814211/52755a49-2962-447e-96d0-dcfb2e864494">

**Comment by jumping2000** [comment]
> se parli di questo: https://github.com/caiosweet/Package-Notification-HUB-AppDaemon l'ho installato.. <img alt="Screenshot 2023-10-31 alle 09 43 55" width="2000" src="https://user-images.githubusercontent.com/814211/279311580-c16fb6d1-7188-4994-9c2d-91fd93024b13.png"> <img alt="Screenshot 2023-10-31 alle 09 44 36" width="1772" src="https://user-images.githubusercontent.com/814211/279311706-52755a49-2962-447e-96d0-dcfb2e864494.png">

Ok, allora lo hai installato ma non hai inserito i notifcation services da usare con il "Centro Notifiche".
Il blueprint è fatto in modo da usare il "Centro Notifiche" oppure i servizi di notifica normali (alexa, google, telegram mobile app):
tu in pratica hai messo hai fatto un mix, mezza conf del centro notifiche e mezza dei servizi normali. dovresti provare o l'una o l'altra modalità di notifica

**Comment by jumping2000** [comment]
closed
